export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE'

export const ADD_TO_CART           = 'ADD_TO_CART'

export const CHECKOUT_SUCCESS      = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE      = 'CHECKOUT_FAILURE'
export const DISPLAY_MESSAGE       = 'DISPLAY_MESSAGE'
