export const REQUEST_ERROR                  = 'REQUEST_ERROR'

export const LOAD_COFFEESHOPS_SUCCESS       = 'LOAD_COFFEESHOPS_SUCCESS'
export const LOAD_COFFEESHOPS_ERROR         = 'LOAD_COFFEESHOPS_ERROR'

export const SAVE_COFFESHOP_SUCCESS         = 'SAVE_COFFESHOP_SUCCESS'
export const SAVE_COFFESHOP_ERROR           = 'SAVE_COFFESHOP_ERROR'

export const LOAD_COFFEESHOP_DETAIL_SUCCESS = 'LOAD_COFFEESHOP_DETAIL_SUCCESS'
export const LOAD_COFFEESHOP_DETAIL_ERROR   = 'LOAD_COFFEESHOP_DETAIL_ERROR'

export const VIEW_DIRECTION_SUCCESS         = 'VIEW_DIRECTION_SUCCESS'
export const VIEW_DIRECTION_ERROR           = 'VIEW_DIRECTION_ERROR'
